######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 19 15:22:19 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
